### ISSUE TITLE
Softwarecategorie

### ISSUE THREAD

**Issue by goto-bus-stop** [IcyPalm/Leertaak3#14]
eg. "os", "office", "educational", "hr"

"os" is de nuttigste voor het selecteren van besturingssystemen van componenten: https://github.com/IcyPalm/Leertaak3/blob/42ce68849fa35df9c6440c82aa1dbdd2ae3f5aef/site/app/Http/Controllers/Components/EditController.php#L34-L38

**Comment by IcyPalm** [comment]
Done, Fixed in #23
