### ISSUE TITLE
Overige eisen

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Leertaak3#21]
- [x] automatische presentatie van relevante aanvullende informatie na het in-voeren van sleutelvelden;
- [x] automatische controle op referentiële integriteit;
- [x] automatische verbandcontroles, bijvoorbeeld: betaaldatum valt na order-datum;

**Comment by goto-bus-stop** [comment]
> automatische controle op referentiële integriteit
doen we gedeeltelijk in controllers met `->validate`, daar kun je namelijk "exists:tabelnaam,kolomnaam" en "unique:tabelnaam,kolomnaam" aan doorgeven om zulke checks uit te voeren

**Comment by IcyPalm** [comment]
Tja... niet iets om nu nog op te gaan letten denk ik. Ik sluit hem, heeft ATM TOTAAL geen prioriteit
