### ISSUE TITLE
Prioriteiten bij Incidents

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Leertaak3#28]
eigenlijk moeten er bij incidents nog prioriteiten bij, iets met impact en bla bla....

**Comment by mrdizzer** [comment]
Urgentie

1=printer
2=werkstation
3=lokale servers
4=Locatieswitch/router
Hoofdkantoor = Urgentie+1

Impact

5= voor hoofdkantoor server/switch/router
4= Borger(1215)server/switch/router/printer
3= gieten(550)/gieterveen(700)/grollo(990) server/switch/router/printer
2= gasselte(330)/anloo/assen(weining :P) server/switch/router/printer
1= lokaal werkstation

(Urgentie+Impact)/2=Prioriteit

**Comment by IcyPalm** [comment]
Voor een grafische weergave kunnen we eventueel gewoon Bootstrap Colors toepassen zie: http://getbootstrap.com/css/#tables-contextual-classes

**Comment by goto-bus-stop** [comment]
6.5!!
