### ISSUE TITLE
Problem Management

### ISSUE THREAD

**Issue by goto-bus-stop** [IcyPalm/Leertaak3#7]
Groepen incidenten vormen problemen. daar moeten we ook een tabelletje voor bijhouden

(en wat fancy automatische detectie)

**Comment by IcyPalm** [comment]
Problem:
 - Name
- Date+Time created(autofill)
- Date+Time fixed(helperfill) (moeten we voor datums nog even een bootstrap/JQuery select maken(ook bij de rest)
- Notes
- List of incidents
